# -*- coding: utf-8 -*-
"""TranformarHosp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eVQoEIQs6ZLuPHMfEBxAgIgBTygUIvN
"""

import pandas as pd
df = pd.read_excel("CitasHospitalSucNorte.xlsx")
df_eps = pd.read_csv("listado-eps-por-regimen-30032022.csv", sep=";")

df.head()

df_eps.head()

df_pacientes = df[['NroSegSocial','nombrePaciente','apellido','telefono','EPS']]
df_pacientes

df_pacientes = df_pacientes.drop_duplicates()
df_pacientes

df_pacientes.count()

df_medicos = df[['tarjeta','Medico']]
df_medicos

df_medicos = df_medicos.drop_duplicates()

df_medicos

df_eps_citas = df[['EPS']]
df_eps_citas

df_eps_citas = df_eps_citas.drop_duplicates()
df_eps_citas

df_eps = df_eps.rename(columns={'CÓDIGO':'EPS'})
df_eps

df_eps_citas = pd.merge(df_eps_citas, df_eps, on='EPS', how='right')

df_eps_citas = df_eps_citas[['EPS','ENTIDAD']]
df_eps_citas

df_historia = df[['NroCita','Diagnostico','Tratamiento']]
df_historia

df_historia.reset_index(level=0,inplace=True)
df_historia

df_historia = df_historia.rename(columns={'index':'idHistoria'})
df_historia

df_historia['idHistoria']+=7
df_historia

df_citas = df[['NroCita','fecha','NroSegSocial','tarjeta','EPS']]
df_citas

df_citas = pd.merge(df_citas, df_historia, on='NroCita', how='right')
df_citas

df_citas = df_citas[['NroCita','fecha','NroSegSocial','tarjeta','EPS','idHistoria']]
df_citas

df_pacientes.to_csv('pacientes.csv', index=False)
df_medicos.to_csv('medicos.csv', index=False)
df_eps_citas.to_csv('eps.csv', index=False)
df_historia.to_csv('historia.csv', index=False)
df_citas.to_csv('citas.csv',index=False)